# Generated by Django 4.2.5 on 2023-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
