# Generated by Django 4.2.5 on 2023-09-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0002_comment_like_cnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="like_cnt",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
